FROM python:3.7

ENV DATABASE_USER=lifehack\
    DATABASE_HOST=postgres\
    DATABASE_PASSWORD=pass\
    DATABASE_NAME=lifehack

WORKDIR /app
COPY . /app

RUN pip install -r requirements.txt

CMD python manage.py

EXPOSE 5000
