FROM nginx

# contentsを配置するディレクトリを作成する
COPY nginx/ /home/work
RUN mkdir -p /var/log/nginx/log\
    && mkdir /home/www \
    && mkdir /home/www/contents

# ビルド環境で構築されたdistディレクトリをnignxの該当のディレクトリに配置する
COPY . /app
RUN cp -r /app/dist /home/www/contens/dist

# nginx.confファイルを配置する
WORKDIR /home/work
RUN rm -f /etc/nginx/conf.d/*.conf \
    && rm -f /etc/nginx/nginx.conf \
    && cp -i *.conf /etc/nginx

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;","-c","/etc/nginx/nginx.conf"]